# Generated by Django 4.2.3 on 2023-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_for_you_app', '0002_alter_category_service_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_service',
            name='employee',
        ),
        migrations.CreateModel(
            name='Category_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='beauty_for_you_app.category_service')),
                ('staff', models.ManyToManyField(to='beauty_for_you_app.staff')),
            ],
        ),
    ]
